export const FETCH_PRODUCTS="FETCH_PRODUCTS"
export const FILTER_PRODUCTS_BY_SIZE="FILTER_PRODUCTS_BY_SIZE"
export const ORDER_PRODUCTS_BY_PRICE="ORDER_PRODUCTS_BY_PRICE"

export const FETCH_CART_ITEMS="FETCH_CART_ITEMS"
export const DELETE_CART_ITEM="DELETE_CART_ITEM"
export const ADD_PRODUCT_TO_CART="ADD_PRODUCT_TO_CART"

export const LOGGING_USER="LOGGING_USER"
export const USER_LOGGIN_SUCCES="USER_LOAD_FAIL"
export const USER_LOGGIN_FAIL="USER_LOAD_FAIL"

export const USER_LOADING="USER_LOADING"
export const USER_LOADED="USER_LOAD_SUCCES"

export const LOGOUT_SUCCES="LOGOUT_SUCCES"

export const REGESTER_USER="REGESTER_USER"
export const USER_REGESTRNG="USER_REGESTRNG"
export const USER_REGESTER_SUCCESS="USER_REGESTER_SUCCES"
export const USER_REGESTER_FAIL="USER_REGESTER_FAIL"

export const AUTH_ERROR="AUTH_ERROR"
export const GET_ERRORS="GET_ERRORS"
export const CLEAR_ERRORS="CLEAR_ERRORS"


export const GET_ORDERS="GET_ORDERS"
export const POST_ORDER_BEGUN="POST_ORDER"
export const POST_ORDER_SUCCESS="POST_ORDER"
export const POST_ORDER_FAIL="POST_ORDER"