export const FETCH_PRODUCTS="FETCH_PRODUCTS"
export const FILTER_PRODUCTS_BY_SIZE="FILTER_PRODUCTS_BY_SIZE"
export const ORDER_PRODUCTS_BY_PRICE="ORDER_PRODUCTS_BY_PRICE"

export const FETCH_CART_ITEMS="FETCH_CART_ITEMS"
export const DELETE_CART_ITEM="DELETE_CART_ITEM"
export const ADD_PRODUCT_TO_CART="ADD_PRODUCT_TO_CART"